default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hello_sample_development

test:
  <<: *default
  database: hello_sample_test

production:
  <<: *default
  database: hello_sample_production
  username: hello_sample
  password: <%= ENV['hello_sample_DATABASE_PASSWORD'] %>
